### ISSUE TITLE
pagination

### ISSUE THREAD

**Issue by Adnan0703** [zeroasterisk/CakePHP-ElasticSearchIndex#2]
I like your plugin but I couldn't find anything on pagination. How can I paginate results if I do not want to show 200 records?

**Comment by zeroasterisk** [comment]
sorry for the very slow response -- I didn't see this question for.... well... I guess 7 months :crying_cat_face: 

The `esSearchGetKeys()` can return any number of primary keys, 200 being the default...  

But you can set whatever you want in your CakePHP `find()` call, which uses the list of primary keys as it's conditions... so you can set `limit/page/order` and it would behave normally.

```
$sortedIds = $this->esSearchGetKeys('Search Term');
for ($i = 1; $i < 10; $i++) { 
  $results = $this->find('all', array(
    'limit' => 10,
    'page' => $i,
    'conditions' => array(
      "{$this->alias}.{$this->primaryKey}" => $sortedIds
    )
  ));
  $results = $this->searchResultsResort($results, $sortedIds);
  debug(compact('i', 'results'));
}
```

---

Sadly, this doesn't _really_ support pagination, as it should.  You can assign the conditions to paginate and it will work. but you'll always be limited to `esSearchGetKeys()` limit.

The primary keys as condition filters effective, but crude.  oh well.
